### ISSUE TITLE
Error while running test data

### ISSUE THREAD

**Issue by maojn** [ablab/TandemTools#1]
Hi,

Thank you for offering tandemtools.

I have installed tandemtools :
conda install --file requirement.txt

and also installed regex and compiled jellyfish after receiving errors (not in installation instruction).
Then I got the following error:

$ /usr/local/apps/tandemtools/tandemquast.py --nano test_data/simulated_reads.fasta test_data/simulated_polished.fa -o test_data/simulated_res
2020-02-25 10:18:52 TandemQUAST started

*********************************
Running TandemMapper...
2020-02-25 10:18:53 TandemMapper started

*********************************
K-mers selection started...

Analyzing simulated-polished assembly
Traceback (most recent call last):
  File "/usr/local/apps/tandemtools/tandemmapper.py", line 83, in <module>
    main()
  File "/usr/local/Anaconda/envs_app/tandemtools/current/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Anaconda/envs_app/tandemtools/current/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Anaconda/envs_app/tandemtools/current/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Anaconda/envs_app/tandemtools/current/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/apps/tandemtools/tandemmapper.py", line 74, in main
    select_kmers.do(assemblies, raw_reads_fname, reads_fname, hifi_reads_fname, out_dir, tmp_dir, no_reuse)
  File "/usr/local/apps/tandemtools/scripts/select_kmers.py", line 157, in do
    with open(assembly.all_kmers_fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/$USER/tandemtools/test_data/simulated_res/simulated-polished_all_kmers.txt'
ERROR: tandemMapper failed! Please check input files and tandemMapper output. TandemQUAST cannot proceed without alignments. 

Did I miss anything during installation? Thank you for your help.

Regards,

Jean

**Comment by almiheenko** [comment]
Hi Jean,

Thank you for reporting the issue. Do you have `$USER` in your error message or did you replace it before the posting? If the former, it's a bit weird - could you try to re-run TandemTools using absolute paths instead of relative ones (e.g.,  -o /data/user/tandemtools/test_data/simulated_res)?

Best regards,
Alla

**Comment by maojn** [comment]
Hi Alla,

Do you have a chance to check the error I received? Thank you.

Jean

**Comment by maojn** [comment]
Hi Alla,

Do you have a chance to check the error I received? Thank you. Regards

Jean

**Comment by almiheenko** [comment]
Hi Jean,

Sorry for the delay! I suspect that the error can be related to Jellyfish. I changed TandemTools to use the installed version of Jellyfish instead of compiling it. Could you please try to update TandemTools and re-install it? I added regex and jellyfish to conda requirements - thank you for reporting these issues.

Alla

**Comment by minalj365** [comment]
Hi There,

I just installed Tandemtools and ran the same command as Jean and got the same error, along with jellyfish error:

2020-11-12 17:10:36 TandemQUAST started

*********************************
Running TandemMapper...
2020-11-12 17:10:37 TandemMapper started

*********************************
K-mers selection started...
Jellyfish is not found in your PATH! Please install Jellyfish and rerun TandemTools. Jellyfish can be installed through conda install jellyfish
ERROR: tandemMapper failed! Please check input files and tandemMapper output. TandemQUAST cannot proceed without alignments

Could you please look into this?

Thanks,
Minal

**Comment by Rashadx86** [comment]
Hi all,

Installing jellyfish from conda didn't seem to install the binary, just the python modules. Installing Jellyfish from source (and adding the resulting bin directory to the path) resolved this error:

https://github.com/gmarcais/Jellyfish


Thanks,
Rashad

**Comment by HLHsieh** [comment]
Hi, 

I encountered this issue as well.
